var rowOne = [
    'en krukkebutik',
    'et regnskabsprogram',
    'Netflix',
    'Spotify',
    'Irma',
    'Netto',
    'nemlig.com',
    'mødestedet',
    'tinder',
    'grindr',
    'dating.dk',
    'snapchat',
    'twitch',
    'youtube',
];

var rowTwo = [
    'døve',
    'blinde',
    'søskende',
    'dværge',
    'rejsende',
    'business folk',
    'event arrangører',
    'diverse godtfolk',
    'proletariatet',
    'de rige',
    'de fattige',
    'Hellerup',
    'hunde',
    'katte',
    'kendte',
];
